'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useUser } from '@clerk/nextjs';
import { Shield } from 'lucide-react';
import { AppSidebar } from '@/components/app-sidebar';
import { PageHeader } from '@/components/page-header';

export default function AIDetectorPage() {
  const router = useRouter();
  const { isSignedIn, isLoaded } = useUser();
  const [inputText, setInputText] = useState('');
  const [result, setResult] = useState<{ isAI: boolean; probability: number } | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);

  useEffect(() => {
    if (isLoaded && !isSignedIn) {
      router.push('/sign-in');
    }
  }, [isLoaded, isSignedIn, router]);

  if (!isLoaded || !isSignedIn) {
    return null;
  }

  const handleDetect = async () => {
    if (!inputText.trim()) return;
    
    setIsAnalyzing(true);
    try {
      const response = await fetch('/api/ai-detect', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: inputText }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to analyze');
      }

      const data = await response.json();
      setResult(data);
    } catch (error) {
      alert(error instanceof Error ? error.message : 'Failed to analyze text');
    } finally {
      setIsAnalyzing(false);
    }
  };

  return (
    <div className="flex h-screen bg-gray-50">
      <AppSidebar />
      
      <div className="flex-1 overflow-y-auto relative">
        <PageHeader />
        {/* Header */}
        <div className="bg-white border-b border-gray-200">
          <div className="max-w-7xl mx-auto px-8 py-6">
            <h1 className="text-3xl font-bold text-gray-900">AI Detector</h1>
            <p className="text-gray-600 mt-2">Detect if text was generated by AI</p>
          </div>
        </div>

        {/* Content */}
        <div className="max-w-4xl mx-auto px-8 py-8">
          <div className="bg-white rounded-lg border border-gray-200 p-6">
            <h3 className="font-semibold text-gray-900 mb-4">Text to Analyze</h3>
            <textarea
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              placeholder="Paste text to check if it was generated by AI..."
              className="w-full h-64 px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500 resize-none"
            />
            <div className="mt-4 flex items-center justify-between">
              <span className="text-sm text-gray-600">{inputText.length} characters</span>
              <button
                onClick={handleDetect}
                disabled={!inputText.trim() || isAnalyzing}
                className="px-6 py-2.5 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
              >
                <Shield className="w-4 h-4" />
                {isAnalyzing ? 'Analyzing...' : 'Detect AI'}
              </button>
            </div>
          </div>

          {result && (
            <div className="mt-6 bg-white rounded-lg border border-gray-200 p-6">
              <h3 className="font-semibold text-gray-900 mb-4">Analysis Result</h3>
              <div className="space-y-4">
                <div className={`p-4 rounded-lg ${result.isAI ? 'bg-red-50 border border-red-200' : 'bg-green-50 border border-green-200'}`}>
                  <div className="flex items-center gap-3">
                    <Shield className={`w-6 h-6 ${result.isAI ? 'text-red-600' : 'text-green-600'}`} />
                    <div>
                      <p className={`font-semibold ${result.isAI ? 'text-red-900' : 'text-green-900'}`}>
                        {result.isAI ? 'AI-Generated Content Detected' : 'Likely Human-Written'}
                      </p>
                      <p className={`text-sm ${result.isAI ? 'text-red-700' : 'text-green-700'}`}>
                        {Math.round(result.probability * 100)}% confidence
                      </p>
                    </div>
                  </div>
                </div>
                
                <div className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span className="text-gray-600">AI Probability</span>
                    <span className="font-medium text-gray-900">{Math.round(result.probability * 100)}%</span>
                  </div>
                  <div className="w-full bg-gray-200 rounded-full h-2">
                    <div
                      className={`h-2 rounded-full ${result.isAI ? 'bg-red-600' : 'bg-green-600'}`}
                      style={{ width: `${result.probability * 100}%` }}
                    />
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
